version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --pid-file=/var/lib/mysql/mysqld.pid
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lanchonete_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "/bin/sh -c 'mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD'"
      interval: 20s
      timeout: 10s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lanchonete_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    ports:
      - "8080:8080"